apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: TmV3Um9vdFBhc3N3b3JkMTIzIQ==
  MYSQL_USER: bGlxdWliYXNlX3VzZXI=
  MYSQL_PASSWORD: U3Ryb25nUGFzc3dvcmQzMjEh
