apiVersion: v1
kind: Secret
metadata:
  name: mysql-app-credentials
  namespace: todoapp
type: Opaque
stringData:
  NAME: todo_db
  USER: liquibase_user
  PASSWORD: StrongPassword321!
  HOST: mysql-0.mysql.mysql.svc.cluster.local
